config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show

  root to: 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :move_to_index, except: :index

  def index
    @tasks = Task.all
  end
    
  def new
    @task = Task.new
  end

  def create
    Task.create(name: task_params[:name], time: task_params[:time], user_id: current_user.id)
    redirect_to action: :index
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    redirect_to action: :index
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to action: :index
  end


  
  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  private
    def task_params
      params.require(:task).permit(:name, :time)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <%= link_to "一覧画面へ", tasks_path %>
      <%= link_to "投稿画面へ", new_task_path %>
      <%= link_to "マイページへ", user_path(current_user.id) %>
    <% else %>
      <%= link_to "ログインする", new_user_session_path, class: 'post' %>
      <%= link_to "新規登録する", new_user_registration_path, class: 'post' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h2>更新する</h2>
<%= form_with model: @task, local: true do |f| %>
    <p>タスク名： <%= f.text_field :name %></p>
    <p>期限： <%= f.date_select :time, 
    use_month_numbers: true  %></p>
    <%= f.submit "送信" %>
<% end %>

app/views/tasks/index.html.erb
<%= link_to "投稿画面へ", new_task_path %>
<% if user_signed_in? %>
  <% @tasks.each do |task| %>
   <p>
    タスク名：<%= task.name %></br>
    期限：<%= task.time %></br>
    <%= task.user.nickname.present? ? "担当者： #{task.user.nickname}" : "登録No.#{task.user.id}" %>
   </p>
   <p>
      <%= link_to "上記を削除", task_path(task), method: :delete, data: {confirm: "削除しますか?"} %>
      <%= link_to "上記を編集", edit_task_path(task), method: :get %>
   </p>
  <% end %>
<% else %>
  <p>ログインしてください</p>
<% end %>

app/views/tasks/new.html.erb
<h1>新規登録</h1>
<%= form_with model: @task, local: true do |f| %>
    <p>タスク名： <%= f.text_field :name %></p>
    <p>期限： <%= f.date_select :time, 
    use_month_numbers: true  %></p>
    <%= f.submit "送信" %>
<% end %>

app/views/users/show.html.erb
<% @user.tasks.each do |task| %>
  <p>
     タスク名：<%= task.name %></br>
      期限：<%= task.time %>
   </p>
<% end %>